# Generated by Django 4.1.7 on 2023-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molo',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
