# Generated by Django 4.1.7 on 2023-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molo', '0002_alter_molo_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molo',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
